package com.scadroid.webservice.request;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.0.0
//
// Created by Quasar Development at 21-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;

import org.ksoap2.serialization.*;

public class APIError extends AttributeContainer implements KvmSerializable
{
    
    public Enums.ErrorCode code=Enums.ErrorCode.OK;
    public String description;

    public APIError() {}

    public APIError (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("code"))
        {	
	        Object obj = soapObject.getProperty("code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.code = Enums.ErrorCode.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.ErrorCode){
                this.code = (Enums.ErrorCode)obj;
            }    
        }
        if (soapObject.hasProperty("description"))
        {	
	        Object obj = soapObject.getProperty("description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.description = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.description = (String)obj;
            }    
        }


    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return code!=null?code.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return description!=null?description:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "code";
            info.namespace= "http://vo.api.scadabr.org.br";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "description";
            info.namespace= "http://vo.api.scadabr.org.br";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

	@Override
	public String getInnerText() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setInnerText(String arg0) {
		// TODO Auto-generated method stub

	}

}
