package com.scadroid.webservice.request;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.0.0
//
// Created by Quasar Development at 21-07-2014
//
//---------------------------------------------------

public interface IServiceEvents
{
    public void Starting();
    public void Completed(@SuppressWarnings("rawtypes") OperationResult result);
}
