

package com.scadroid.webservice.request;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.0.0
//
// Created by Quasar Development at 21-07-2014
//
//---------------------------------------------------

import android.view.View;

import java.util.ArrayList;
import java.util.List;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;

public class API
{
    interface WIQIWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(ExtendedSoapSerializationEnvelope envelope, Object result) throws Exception;
    }

    public String url;
    public boolean permissao_login = false;

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;
    
    public API (IServiceEvents callback)
    {
        this.callback = callback;
    }

    public API(IServiceEvents callback, String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public API(IServiceEvents callback,String url,int timeOut) {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    public API() {}

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                return new HttpsTransportSE(uri.getHost(), uri.getPort(), uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope();
        return envelope;
    }

    protected void sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport) throws Exception
    {
        transport.call(methodName, envelope,httpHeaders);
    }


    Object getResult(@SuppressWarnings("rawtypes") Class destObj,Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }

        return null;
    }

    public GetStatusResponse getStatus() throws Exception
    {
        return (GetStatusResponse)execute(new WIQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://config.api.scadabr.org.br", "getStatus");
                __envelope.setOutputSoapObject(__soapReq);

                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (GetStatusResponse)getResult(GetStatusResponse.class,__result,"GetStatusResponse",__envelope);
            }
        },"");
    }

    @SuppressWarnings("rawtypes")
    public android.os.AsyncTask getStatusAsync()
    {
        return executeAsync(new Functions.IFunc< GetStatusResponse >() {
            public GetStatusResponse Func() throws Exception {
                return getStatus();
            }
        });
    }

    public BrowseTagsResponse browseTags(final String browseTagsParams, final BrowseTagsOptions browseTagsOptions ) throws Exception
    {
        return (BrowseTagsResponse)execute(new WIQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://config.api.scadabr.org.br", "browseTags");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("itemsPath");
                __info.setType(String.class);
                __info.setValue(browseTagsParams);
                __soapReq.addProperty(__info); //-->linha debugada

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("options");
                __info.setType(BrowseTagsOptions.class);
                __info.setValue(browseTagsOptions);
                __soapReq.addProperty(__info); // linha debugada

                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (BrowseTagsResponse)getResult(BrowseTagsResponse.class,__result,"BrowseTagsResponse",__envelope);
            }
        },"");
    }

    @SuppressWarnings("rawtypes")
    public android.os.AsyncTask browseTagsAsync(final String browseTagsParams, final BrowseTagsOptions browseTagsOptions)
    {
        return executeAsync(new Functions.IFunc< BrowseTagsResponse>() {
            public BrowseTagsResponse Func() throws Exception {
                return browseTags(browseTagsParams, browseTagsOptions);
            }
        });
    }

    public ReadDataResponse readData(final ArrayList<String> readDataParams, final ReadDataOptions readDataOptions ) throws Exception
    {
        return (ReadDataResponse)execute(new WIQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://config.api.scadabr.org.br", "readData");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;

                for(int x = 0; x < readDataParams.size(); x ++){
                    __info = new PropertyInfo();
                    __info.setNamespace("http://config.api.scadabr.org.br");
                    __info.setName("itemPathList");
                    __info.setType(readDataParams.getClass());
                    __info.setValue(readDataParams.get(x));
                    __soapReq.addProperty(__info); //-->linha debugada
                }

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("options");
                __info.setType(BrowseTagsOptions.class);
                __info.setValue(readDataOptions);
                __soapReq.addProperty(__info); // linha debugada

                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ReadDataResponse)getResult(ReadDataResponse.class,__result,"ReadDataResponse",__envelope);
            }
        },"");
    }

    @SuppressWarnings("rawtypes")
    public android.os.AsyncTask readDataAsync(final ArrayList<String> readDataParams, final ReadDataOptions readDataOptions)
    {
        return executeAsync(new Functions.IFunc<ReadDataResponse>() {
            public ReadDataResponse Func() throws Exception {
                return readData(readDataParams, readDataOptions);
            }
        });
    }

    public WriteDataResponse writeData(final ArrayList<ItemStringValue> itemValueList, final WriteDataOptions writeDataOptions ) throws Exception
    {
        return (WriteDataResponse)execute(new WIQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://config.api.scadabr.org.br", "writeStringData");
                new MarshalDate().register(__envelope);
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;

                for(int x = 0; x < itemValueList.size(); x ++){
                    __info = new PropertyInfo();
                    __info.setNamespace("http://config.api.scadabr.org.br");
                    __info.setName("itemsList");
                    __info.setType(itemValueList.getClass());
                    __info.setValue(itemValueList.get(x));
                    __soapReq.addProperty(__info); //-->linha debugada
                }

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("options");
                __info.setType(WriteDataOptions.class);
                __info.setValue(writeDataOptions);
                __soapReq.addProperty(__info); // linha debugada


                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WriteDataResponse)getResult(WriteDataResponse.class,__result,"WriteStringDataResponse",__envelope);
            }
        },"");
    }

    @SuppressWarnings("rawtypes")
    public android.os.AsyncTask writeDataAsync(final ArrayList<ItemStringValue> itemValueList, final WriteDataOptions writeDataOptions)
    {
        return executeAsync(new Functions.IFunc<WriteDataResponse>() {
            public WriteDataResponse Func() throws Exception {
                return writeData(itemValueList, writeDataOptions);
            }
        });
    }

    public GetDataHistoryResponse getDataHistory(final String itemName, final GetDataHistoryOptions options) throws Exception
    {
        return (GetDataHistoryResponse)execute(new WIQIWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();

                SoapObject __soapReq = new SoapObject("http://config.api.scadabr.org.br", "getDataHistory");
                new MarshalDate().register(__envelope);
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("itemName");
                __info.setType(String.class);
                __info.setValue(itemName);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.setNamespace("http://config.api.scadabr.org.br");
                __info.setName("options");
                __info.setType(GetDataHistoryOptions.class);
                __info.setValue(options);
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (GetDataHistoryResponse)getResult(GetDataHistoryResponse.class,__result,"GetDataHistoryResponse",__envelope);
            }
        },"");
    }

    @SuppressWarnings("rawtypes")
    public android.os.AsyncTask getDataHistoryAsync(final String itemName, final GetDataHistoryOptions options)
    {
        return executeAsync(new Functions.IFunc< GetDataHistoryResponse>() {
            public GetDataHistoryResponse Func() throws Exception {
                return getDataHistory(itemName,options);
            }
        });
    }

    protected Object execute(WIQIWcfMethod wcfMethod,String methodName) throws Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    protected < T> android.os.AsyncTask<Void, Void, OperationResult<T>>  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }




    Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {
        return new Exception(fault.faultstring);
    }
}