package com.scadroid.webservice.request;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 7/22/2014 2:10:02 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.Hashtable;

import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

public class BrowseTagsOptions extends AttributeContainer implements KvmSerializable{
   
	public Integer maxReturnField;
    
    public BrowseTagsOptions(){}
    
    public BrowseTagsOptions(Integer maxReturnField) {
    	this.maxReturnField = maxReturnField;
    }
    
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return maxReturnField;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 1;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "maxReturn";
                info.namespace= "http://config.api.scadabr.org.br";
                break;
        }
    }
    
    @Override
    public void setProperty(int index, Object value) {
	    switch(index){
	        case 0:
	        	maxReturnField = Integer.parseInt(value.toString()) ; ;
	        	break;
	    	}
    }

	@Override
	public String getInnerText() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setInnerText(String arg0) {
		// TODO Auto-generated method stub

	}
   
}
